from typing import TypedDict, List

class AgentState(TypedDict):
    question: str          # the original user question, never modified after set
    plan: List[str]        # retrieval steps generated by the Planner
    retrieved_docs: List[str]  # raw text chunks returned by the Retriever
    answer: str            # final answer generated by the Critic
    critique: str          # reserved for future use (leave as empty string for now)